services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libpq-dev gcc
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
