"""add_kyc_tables

Revision ID: e5b91a541754
Revises: 72d19aba6366
Create Date: 2025-07-20 05:59:43.810734+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b91a541754'
down_revision: Union[str, None] = '72d19aba6366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'status',
               existing_type=postgresql.ENUM('requested', 'offered', 'accepted', 'completed', 'cancelled', name='ridestatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'status',
               existing_type=postgresql.ENUM('requested', 'offered', 'accepted', 'completed', 'cancelled', name='ridestatus'),
               nullable=True)
    # ### end Alembic commands ###
