"""Add OTP fields to User model

Revision ID: df0b8d7fda65
Revises: 61e6ea6b951e
Create Date: 2025-07-08 17:31:33.821204+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0b8d7fda65'
down_revision: Union[str, None] = '61e6ea6b951e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_valid_until', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_verified')
    op.drop_column('users', 'otp_valid_until')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
