"""fix ride status enum to lowercase values

Revision ID: 9df7da1b8053
Revises: cc87646af002
Create Date: 2025-07-18 06:18:44.818802+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df7da1b8053'
down_revision: Union[str, None] = 'cc87646af002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
