"""add 'offered' to ridestatus enum

Revision ID: 72d19aba6366
Revises: 9df7da1b8053
Create Date: 2025-07-18 07:07:46.109177+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d19aba6366'
down_revision: Union[str, None] = '9df7da1b8053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
