"""add_firebase_uid_to_user

Revision ID: cc87646af002
Revises: df0b8d7fda65
Create Date: 2025-07-15 04:45:26.268363+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc87646af002'
down_revision: Union[str, None] = 'df0b8d7fda65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.add_column('users', sa.Column('aadhar_card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('vehicle_registration', sa.String(), nullable=True))
    op.add_column('users', sa.Column('insurance_document', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'insurance_document')
    op.drop_column('users', 'vehicle_registration')
    op.drop_column('users', 'aadhar_card')
    op.drop_column('users', 'firebase_uid')
    op.drop_column('rides', 'offered_at')
    # ### end Alembic commands ###
